// <auto-generated />
using System;
using DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbContext.Migrations
{
    [DbContext(typeof(csMainDbContext.SqlServerDbContext))]
    [Migration("20240307103415_initial_migration")]
    partial class initial_migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.TicketInformation", b =>
                {
                    b.Property<string>("Artikelnamn")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Logorad1")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Logorad2")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Pris")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Venue")
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("WebbUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Webbläst")
                        .HasColumnType("datetime2");

                    b.Property<string>("barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("dateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("datumStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("namn1")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("namn2")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("platsbokadGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("status")
                        .HasColumnType("tinyint");

                    b.Property<int?>("stolsnr")
                        .HasColumnType("int");

                    b.Property<string>("stolsrad")
                        .HasColumnType("nvarchar(200)");

                    b.ToTable((string)null);

                    b.ToView("Vy_MobileTicket", "dbo");
                });

            modelBuilder.Entity("Models.TicketKundInfo", b =>
                {
                    b.Property<string>("Bokatav")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("BokningsNr")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("WebbUid")
                        .HasColumnType("uniqueidentifier");

                    b.ToTable((string)null);

                    b.ToView("Vy_BookingInformation", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
